version: "3"

services:
  music-mongo:
    image: mongo:4.4.14
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: fullstack
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
volumes:
  data:
